### ISSUE TITLE
build.gradle uses old maven

### ISSUE THREAD

**Issue by wyvest** [Ab20zipYT/forge-template#1]
self-explanatory, you even PRed it in hytilities!! oh wait

**Comment by Ab20zipYT** [comment]
I didn't understand what you mean to say. Please elaborate.

**Comment by wyvest** [comment]
> I didn't understand what you mean to say. Please elaborate.

this uses files.minecraftforge.net instead of the newer one.

**Comment by Ab20zipYT** [comment]
oh oh wait it is fixed in the new commit
