### ISSUE TITLE
annotationProcessor should be used

### ISSUE THREAD

**Issue by wyvest** [Ab20zipYT/forge-template#5]
this is so spongegradle can make a refmap

**Comment by Ab20zipYT** [comment]
No need of annotationProcessor when using shadow already.

**Comment by wyvest** [comment]
> No need of annotationProcessor when using shadow already.

no??? without an annotationProcessor mixin cannot make a refmap

**Comment by Ab20zipYT** [comment]
U see the latest release and see if it has a refmap
also, u can build it yourself and check if it generates a refmap or not
