### ISSUE TITLE
build.gradle uses buildscript and not plugins

### ISSUE THREAD

**Issue by wyvest** [Ab20zipYT/forge-template#9]
instead of using buildscript, use plugins (like https://github.com/asbyth/ForgeTemplate/blob/master/build.gradle#L1-L5 and https://github.com/asbyth/ForgeTemplate/blob/master/settings.gradle)

**Comment by Ab20zipYT** [comment]
It is my style to work.

**Comment by wyvest** [comment]
> It is my style of coding :)

its an old and inefficient style of coding

**Comment by Ab20zipYT** [comment]
Nah
